language: go

go:
    - 1.12.1

services:
    - postgresql

addons:
    postgresql: 9.6

env:
    global:
        - GO111MODULE=on
        - CONNECTION_STRING="host=localhost sslmode=disable user=postgres port=5432"

install:
    - ${TRAVIS_BUILD_DIR}/scripts/build.sh

before_script:
    - dappctrl db-create -conn "${CONNECTION_STRING} dbname=postgres"
    - dappctrl db-migrate -conn "${CONNECTION_STRING} dbname=dappctrl"

script:
    - ${TRAVIS_BUILD_DIR}/scripts/test.sh


notifications:
    slack:
        rooms:
            - privatix:ntmw2wh4PAHoodqtMc95KFDt#dapp-tech
