language: go

go:
    - 1.12.1

addons:
    postgresql: "10"
    apt:
        packages:
            - postgresql-10
env:
    global:
        - GO111MODULE=on
        - PGPORT=5432
        - PGUSER=postgres

install:
    - ${TRAVIS_BUILD_DIR}/scripts/build.sh

before_script:
    # create database
    - CONNECTION_STRING="host=localhost sslmode=disable user=${PGUSER} port=${PGPORT}"
    - dappctrl db-create -conn "${CONNECTION_STRING} dbname=postgres"
    - dappctrl db-migrate -conn "${CONNECTION_STRING} dbname=dappctrl"

script:
    - ${TRAVIS_BUILD_DIR}/scripts/test.sh


notifications:
    slack:
        rooms:
            - privatix:ntmw2wh4PAHoodqtMc95KFDt#dapp-tech
