language: go

go:
    - 1.12.1

services:
    - postgresql

addons:
    postgresql: 9.6

env:
    global:
        - GO111MODULE=on

install:
    - ${TRAVIS_BUILD_DIR}/scripts/build.sh

before_script:
    - ${TRAVIS_BUILD_DIR}/scripts/create_database.sh

script:
    - ${TRAVIS_BUILD_DIR}/scripts/test.sh


notifications:
    slack:
        rooms:
            - privatix:ntmw2wh4PAHoodqtMc95KFDt#dapp-tech
